<<<<<<< HEAD
# =============================================
# Jekyll configuration
# =============================================

# Where things are
source:           ./source
destination:      ./build
layouts_dir:      _jekyll/_layouts
includes_dir:     _jekyll/_includes
data_dir:         _jekyll/_data
=======
---
title: Selena Lee Official Website
timezone: UTC
>>>>>>> f4eb3a4eda6595ae436a99dbc621eb650bee8fb4
collections:
  beauty:
    output:       true
  filmography:
    output:       true
  schedule:
    output:       true
  press:
    output:       true

# Outputting
permalink:        pretty
defaults:
<<<<<<< HEAD
  - scope:
      path:       ""
      type:       pages
    values:
      layout:     base
  - scope:
      path:       ""
      type:       beauty
    values:
      layout:     post-beauty
  - scope:
      path:       ""
      type:       filmography
    values:
      layout:     post-filmography
  - scope:
      path:       ""
      type:       schedule
    values:
      layout:     post-schedule
  - scope:
      path:       ""
      type:       press
    values:
      layout:     post-press

# =============================================
# Site metadata
# =============================================

# General
title:            Selena Lee Official Website
url:              http://selena-lee.com
since:            2006

# Accounts
analytics:        UA-12048611-1
=======
- scope:
    path: ''
    type: pages
  values:
    layout: base
- scope:
    path: ''
    type: beauty
  values:
    layout: post-beauty
- scope:
    path: ''
    type: filmography
  values:
    layout: post-filmography
source: "./"
destination: "./build"
layouts_dir: _jekyll/_layouts
includes_dir: _jekyll/_includes
data_dir: _jekyll/_data
url: http://selena-lee.com
since: 2006
analytics: UA-12048611-1
>>>>>>> f4eb3a4eda6595ae436a99dbc621eb650bee8fb4
selena:
  facebook:       selenaleelalee
  instagram:      selenaleelalee
  youtube:        selenabeautytips
  weibo:          1731864915
  tencent:        selenaliszewan
fanclub:
<<<<<<< HEAD
  twitter:        selenalicom
  instagram:      selenaleeofficial
  vimeo:          selenalicom
  weibo:          selenaliofficial
  tencent:        selenaliofficial
=======
  twitter: selenalicom
  instagram: selenaleeofficial
  vimeo: selenalicom
  weibo: selenaliofficial
  tencent: selenaliofficial
>>>>>>> f4eb3a4eda6595ae436a99dbc621eb650bee8fb4
