# =============================================
# Jekyll configuration
# =============================================

# Where things are
source:                 source
destination:            build
layouts_dir:            _jekyll/_layouts
includes_dir:           _jekyll/_includes
data_dir:               _jekyll/_data
plugins_dir:            _jekyll/_plugins
sass:
  style:                compressed
collections:
  filmography:
    output:             true

# Handling reading
strict_front_matter:    true

# Plugins
plugins:
  - jekyll-sitemap

# Conversion
markdown:               kramdown

# Custom metadata
url:                    'https://selena.netlify.com'
baseurl:                ''

# Outputting
permalink:              pretty
defaults:
  - scope:
      path:             ''
      type:             pages
    values:
      layout:           base
  - scope:
      path:             'en'
    values:
      language:         en
  - scope:
      path:             'zh'
    values:
      language:         zh
  - scope:
      path:             'en/filmography'
    values:
      type:             filmography
      layout:           post-filmography
  - scope:
      path:             'zh/filmography'
    values:
      type:             filmography
      layout:           post-filmography

# Markdown Processors
kramdown:
  auto_ids:             false

# =============================================
# Site metadata
# =============================================
# General
since:            2006

# Accounts
analytics:        UA-12048611-1
selena:
  facebook:       selenaleelalee
  instagram:      selenaleelalee
  youtube:        selenabeautytips
  weibo:          1731864915
  tencent:        selenaliszewan
fanclub:
  twitter:        selenalicom
  instagram:      selenaleeofficial
  vimeo:          selenalicom
  weibo:          selenaliofficial
  tencent:        selenaliofficial