# =============================================
# Jekyll configuration
# =============================================

# Where things are
source:           ./source
destination:      ./build
layouts_dir:      _jekyll/_layouts
includes_dir:     _jekyll/_includes
data_dir:         _jekyll/_data
collections:
  beauty:
    output:       true
  filmography:
    output:       true

# Outputting
defaults:
  -
    scope:
      path:       ""
      type:       pages
    values:
      layout:     base
  -
    scope:
      path:       ""
      type:       beauty
    values:
      layout:     post-beauty
  -
    scope:
      path:       ""
      type:       filmography
    values:
      layout:     post-filmography

# =============================================
# Site metadata
# =============================================

# General
title:            Selena Lee Official Website
url:              http://selena-lee.com
since:            2006

# Accounts
analytics:        UA-12048611-1
selena:
  facebook:       selenaleelalee
  instagram:      selenaleelalee
  youtube:        selenabeautytips
  weibo:          1731864915
  tencent:        selenaliszewan
fanclub:
  twitter:        selenalicom
  instagram:      selenaleeofficial
  vimeo:          selenalicom
  weibo:          selenaliofficial
  tencent:        selenaliofficial

# =============================================
# CMS configuration
# =============================================

prose:
  rooturl: 'source'
  siteurl: 'https://selena.netlify.com/'
  media: 'uploads'
  ignore:
    - _jekyll
    - assets
  metadata:
    _beauty:
      - name: "date"
        field:
          element: "text"
          label: "Date"
      - name: "videoID"
        field:
          element: "text"
          label: "YouTube ID"
    _filmography:
      - name: "genre"
        field:
          element: "select"
          label: "Genre"
          options:
            - name: "Ancient"
              value: "ancient"
            - name: "Modern
              value: "modern"
            - name: "Pre-modern"
              value: "pre-modern"
      - name: "episodes"
        field:
          element: "number"
          label: "Number of episodes"
      - name: "synopsis"
        field:
          element: "textarea"
          label: "Synopsis"
      - name: "image"
        field:
          element: "checkbox"
          label: "Image?"
