# =============================================
# Build config
# =============================================

src:              src
build:            build

# Templates
templates:        <%= site.src %>/templates
layouts:          <%= site.templates %>/layouts
partials:         <%= site.templates %>/partials

# Pages & data
pages:            <%= site.src %>/pages
data:             <%= site.src %>/data


# =============================================
# Site metadata
# =============================================

title:            Selena Lee Official Website
description:      Actress / Host / Enterpreneur / Beauty Guru
url:              http://selena-li.com
since:            2006

# Site areas
filmography:
  title:          Filmography
  subtitle:       Television dramas and movies
beauty:
  title:          Beauty
  subtitle:       Make-up tutorials and tips
schedule:
  title:          Schedule
  subtitle:       Functions and events
press:
  title:          Press
  subtitle:       News articles and interviews

# Social media
selena:
  facebook:       selenaleelalee
  instagram:      selenaleelalee
  youtube:        selenabeautytips
  weibo:          1731864915
  tencent:        selenaliszewan
fanclub:
  twitter:        selenalicom
  instagram:      selenaleeofficial
  vimeo:          selenalicom
  weibo:          selenaliofficial
  tencent:        selenaliofficial